name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Install
        run: docker-compose exec -i app npm install
      - name: Run Dev
        run: docker-compose exec -i app npm run dev
