name: Build and deploy to gh-page
on: [push, pull_request]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Install
        run: docker-compose exec -i app npm ci
      - name: Build
        run: docker-compose exec -i app npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/dist # The folder the action should deploy.
